package com.manishjajoriya.transferlisten.domain.model.search

data class Item(
    val accessType: Any,
    val adSupportedStreamReady: Boolean,
    val album: Album,
    val allowStreaming: Boolean,
    val artist: Artist,
    val artists: List<Artist>,
    val audioModes: List<String>,
    val audioQuality: String,
    val bpm: Any,
    val copyright: String,
    val djReady: Boolean,
    val duration: Int,
    val editable: Boolean,
    val explicit: Boolean,
    val id: Int,
    val isrc: String,
    val mediaMetadata: MediaMetadata,
    val mixes: Mixes,
    val payToStream: Boolean,
    val peak: Double,
    val popularity: Int,
    val premiumStreamingOnly: Boolean,
    val replayGain: Double,
    val spotlighted: Boolean,
    val stemReady: Boolean,
    val streamReady: Boolean,
    val streamStartDate: String,
    val title: String,
    val trackNumber: Int,
    val upload: Boolean,
    val url: String,
    val version: Any,
    val volumeNumber: Int
)